Adicionada rotina para remoção de cometários
UnifespCodeLab/plasmedis-api pull request #25
Opened 2022-01-23 22:14 UTC by AndrewCampos

### O que foi feito:
O comentário é removido através de uma request DELETE no endpoint `/comentarios`. A request deve conter o username do usuário logado e o ID do comentário a ser removido. O comentário apenas é removido se for de autoria do usuário ou se o usuário for administrador.

### Como testar:
Realizar uma request `DELETE /comentarios` com o seguinte body:
`{
    "username": <nome do usuário>,
    "comentario_id": <id do comentário>
}`

#### Cenários:
- [ ] Usuário ou comentários inexistentes: API retorna `{"error": "Informações de usuário ou comentário inválidas"}`
- [ ] Informações válidas e usuário com permissão para alterar: API retorna `{"message": "Comentário removido com sucesso"}`
- [ ] Informações válidas e usuário sem permissão para alterar: API retorna `{"error": "O usuário não tem autorização para essa ação"}`
- [ ] Conteúdo da requisição não é JSON: API retorna `{"error": "A requisição não está no formato esperado"}`

2022-01-24 00:18 UTC, DanielSalis commented on app.py
> +            privilegio_adm = Privilegio.query.filter_by(id='Admin').first()
Mano aqui no lugar de "id=Admin" não deveria ser "user_type='Admin' " :thinking:

2022-01-24 00:20 UTC, DanielSalis commented on app.py
> +            if usuario.id == comentario.id or usuario.user_type == privilegio_adm.id:
Aqui eu acho poderia ser `usuario.id = comentário.criador` :grimacing:

2022-01-24 14:10 UTC, AndrewCampos commented
@DanielSalis realmente, confundi esses dois pontos na hora de enviar. Vou corrigir aqui

2022-01-24 21:04 UTC, DanielSalis commented on app.py
>              usuario = Usuario.query.filter_by(user_name=data['username']).first()
```suggestion
            usuario = Usuario.query.filter_by(user_name=data['user_name']).first()
```

2022-01-24 21:38 UTC, dsalexan requested changes

2022-01-24 21:38 UTC, dsalexan commented on app.py
> +            usuario = Usuario.query.filter_by(user_name=data['username']).first()
Aqui deveria usar na verdade o id do usuário informado no bearer token, não um username informado no body.
Como não tem nenhum exemplo disso hoje em dia no código, escrevi um guia no notion (em [PlaSMeDIS > Guias de Uso > [API] Usuario Autenticado](https://www.notion.so/API-Usu-rio-Autenticado-193c8d8b0dd44c2c940616d4b15ab5a6))

2022-01-31 23:52 UTC, DanielSalis approved these changes
@dsalexan

2022-02-05 14:25 UTC, merged