Update users/<id> PUT and added email
UnifespCodeLab/plasmedis-api pull request #54
Opened 2022-02-07 23:57 UTC by Maegima

### O que foi feito:
Modificado o endpoint para modificar usuários, adicionado email como opção para modificação. Agora todos os parâmetros passados são opcionais.

### Como testar:
`python3 app.py`

#### endpoint PUT /users/<id>
` curl -H "Authorization: Bearer <token>" \
127.0.0.1:8000/categorias/<id> -X PUT -H "Content-type: Application/json" -d '{"nome": "Sem Categoria"}'`

#### Cenários:
- [ ] Modificar email do usuário;
- [ ] Modificar somente um parametro da lista ["email", "real_name", "verificado", "sexo", "nascimento", "cor", "telefone", "rua", "numero_casa"];

2022-02-10 21:24 UTC, dsalexan requested changes

2022-02-10 21:24 UTC, dsalexan commented on app.py
> +            data["verificado"] = True
Isso aqui me deixou um pouco confuso só. Era pra se tiver "verificado" no json da request ele automaticamente seta como true no banco?

2022-02-10 22:07 UTC, Maegima commented on app.py
> +            data["verificado"] = True
Ele já funcionava assim antes então manti o mesmo comportamento.

2022-02-10 22:15 UTC, Maegima commented on app.py
> +            data["verificado"] = True
Na verdade também acho que não faz sentido mesmo ele verificar só de fazer o put sem especificar que vc quer verificar.

2022-02-11 18:50 UTC, Maegima commented
@dsalexan coloquei a issue pra adicionar a modificação de tipo de usuário nesse pull também.
Modifiquei o PUT /users/<id> pra verificar o tipo de usuário antes de fazer os testes e criei um PUT /users/ pra modificar os parâmetros do próprio usuário sem precisar passar id.

2022-02-12 15:07 UTC, DanielSalis approved these changes

2022-02-21 11:34 UTC, dsalexan approved these changes

2022-02-21 11:35 UTC, merged